# coding: utf-8

"""
    EVO API

    Use the DNS of your gym as the User and the Secret Key as the password.The authentication method used in the integration is Basic Authentication  # noqa: E501

    OpenAPI spec version: v1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.member_membership_api import MemberMembershipApi  # noqa: E501
from swagger_client.rest import ApiException


class TestMemberMembershipApi(unittest.TestCase):
    """MemberMembershipApi unit test stubs"""

    def setUp(self):
        self.api = MemberMembershipApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_api_v1_membermembership_cancellation_post(self):
        """Test case for api_v1_membermembership_cancellation_post

        Cancel MemberMembership  # noqa: E501
        """
        pass

    def test_api_v1_membermembership_id_member_membership_get(self):
        """Test case for api_v1_membermembership_id_member_membership_get

        Get summary of MemberMemberships by id  # noqa: E501
        """
        pass

    def test_api_v2_membermembership_get(self):
        """Test case for api_v2_membermembership_get

        Get summary of canceled MemberMemberships  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
