# coding: utf-8

"""
    EVO API

    Use the DNS of your gym as the User and the Secret Key as the password.The authentication method used in the integration is Basic Authentication  # noqa: E501

    OpenAPI spec version: v1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.periodizacao_api_view_model import PeriodizacaoApiViewModel  # noqa: E501
from swagger_client.rest import ApiException


class TestPeriodizacaoApiViewModel(unittest.TestCase):
    """PeriodizacaoApiViewModel unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testPeriodizacaoApiViewModel(self):
        """Test PeriodizacaoApiViewModel"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.periodizacao_api_view_model.PeriodizacaoApiViewModel()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
