# coding: utf-8

"""
    EVO API

    Use the DNS of your gym as the User and the Secret Key as the password.The authentication method used in the integration is Basic Authentication  # noqa: E501

    OpenAPI spec version: v1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import evo_client
from evo_client.models.w12_utils_webhook_filter_view_model import (
    W12UtilsWebhookFilterViewModel,
)  # noqa: E501
from evo_client.rest import ApiException


class TestW12UtilsWebhookFilterViewModel(unittest.TestCase):
    """W12UtilsWebhookFilterViewModel unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testW12UtilzWebHookFilterViewModel(self):
        """Test W12UtilzWebHookFilterViewModel"""
        # FIXME: construct object with mandatory attributes with example values
        # model = evo_client.models.w12_utils_webhook_filter_view_model.W12UtilsWebhookFilterViewModel()  # noqa: E501
        pass


if __name__ == "__main__":
    unittest.main()
