[project]
name = "evo_client"
version = "1.0.0"
description = "ABC Evo SDK"
authors = [
    {email = "support@evo.com"}
]
dependencies = [
    "urllib3>=1.15",
    "six>=1.10", 
    "certifi",
    "python-dateutil",
    "pydantic>=2.0.0",
    "requests>=2.25.0"
]
keywords = ["Swagger", "EVO SDK"]
readme = "README.md"
requires-python = ">=3.8"

[project.urls]
Documentation = "https://evo-integracao.w12app.com.br/swagger/v1/swagger.json"

[build-system]
requires = ["setuptools>=21.0.0"]
build-backend = "setuptools.build_meta"
