# coding: utf-8

"""
    EVO API

    Use the DNS of your gym as the User and the Secret Key as the password.The authentication method used in the integration is Basic Authentication  # noqa: E501

    OpenAPI spec version: v1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import evo_client
from evo_client.models.convenios_api_view_model import (
    ConveniosApiViewModel,
)  # noqa: E501
from evo_client.rest import ApiException


class TestConveniosApiViewModel(unittest.TestCase):
    """ConveniosApiViewModel unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testConveniosApiViewModel(self):
        """Test ConveniosApiViewModel"""
        # FIXME: construct object with mandatory attributes with example values
        # model = evo_client.models.convenios_api_view_model.ConveniosApiViewModel()  # noqa: E501
        pass


if __name__ == "__main__":
    unittest.main()
