# coding: utf-8

"""
    EVO API

    Use the DNS of your gym as the User and the Secret Key as the password.The authentication method used in the integration is Basic Authentication  # noqa: E501

    OpenAPI spec version: v1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import pytest
from evo_client.models.cost_center_api_view_model import CostCenterApiViewModel


@pytest.fixture
def cost_center_api_view_model():
    return CostCenterApiViewModel(
        idCostCenter=1,
        description="Main Cost Center",
        idCostCenterFather=None,
        active=True,
        idDreGroup=10,
        level=1,
    )


def test_cost_center_api_view_model_creation(cost_center_api_view_model):
    """Test creating a CostCenterApiViewModel instance"""
    assert isinstance(cost_center_api_view_model, CostCenterApiViewModel)
    assert cost_center_api_view_model.id_cost_center == 1
    assert cost_center_api_view_model.description == "Main Cost Center"
    assert cost_center_api_view_model.active is True
    assert cost_center_api_view_model.id_dre_group == 10
    assert cost_center_api_view_model.level == 1


def test_cost_center_api_view_model_to_dict(cost_center_api_view_model):
    """Test converting CostCenterApiViewModel to dictionary"""
    model_dict = cost_center_api_view_model.to_dict()

    assert isinstance(model_dict, dict)
    assert model_dict["idCostCenter"] == 1
    assert model_dict["description"] == "Main Cost Center"
    assert model_dict["active"] is True
    assert model_dict["idDreGroup"] == 10
    assert model_dict["level"] == 1


def test_cost_center_api_view_model_equality(cost_center_api_view_model):
    """Test equality comparison of CostCenterApiViewModel instances"""
    same_model = CostCenterApiViewModel(
        idCostCenter=1,
        description="Main Cost Center",
        idCostCenterFather=None,
        active=True,
        idDreGroup=10,
        level=1,
    )

    different_model = CostCenterApiViewModel(
        idCostCenter=2,
        description="Secondary Cost Center",
        idCostCenterFather=1,
        active=False,
        idDreGroup=20,
        level=2,
    )

    assert cost_center_api_view_model == same_model
    assert cost_center_api_view_model != different_model
    assert cost_center_api_view_model != 1
