# coding: utf-8

"""
    EVO API

    Use the DNS of your gym as the User and the Secret Key as the password.The authentication method used in the integration is Basic Authentication  # noqa: E501

    OpenAPI spec version: v1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import pytest
from evo_client.models.dados_contrato_trasnferencia_api_view_model import (
    DadosContratoTrasnferenciaApiViewModel,
)


@pytest.fixture
def dados_contrato_trasnferencia_api_view_model():
    return DadosContratoTrasnferenciaApiViewModel(
        flTransfer=True, idMemberTransfer=123, idMemberMembershipTransfer=456
    )


def test_dados_contrato_trasnferencia_api_view_model_creation(
    dados_contrato_trasnferencia_api_view_model,
):
    """Test creating a DadosContratoTrasnferenciaApiViewModel instance"""
    assert isinstance(
        dados_contrato_trasnferencia_api_view_model,
        DadosContratoTrasnferenciaApiViewModel,
    )
    assert dados_contrato_trasnferencia_api_view_model.fl_transfer is True
    assert dados_contrato_trasnferencia_api_view_model.id_member_transfer == 123
    assert (
        dados_contrato_trasnferencia_api_view_model.id_member_membership_transfer == 456
    )


def test_dados_contrato_trasnferencia_api_view_model_to_dict(
    dados_contrato_trasnferencia_api_view_model,
):
    """Test converting DadosContratoTrasnferenciaApiViewModel to dictionary"""
    model_dict = dados_contrato_trasnferencia_api_view_model.to_dict()

    assert isinstance(model_dict, dict)
    assert model_dict["flTransfer"] is True
    assert model_dict["idMemberTransfer"] == 123
    assert model_dict["idMemberMembershipTransfer"] == 456


def test_dados_contrato_trasnferencia_api_view_model_equality(
    dados_contrato_trasnferencia_api_view_model,
):
    """Test equality comparison of DadosContratoTrasnferenciaApiViewModel instances"""
    same_model = DadosContratoTrasnferenciaApiViewModel(
        flTransfer=True, idMemberTransfer=123, idMemberMembershipTransfer=456
    )

    different_model = DadosContratoTrasnferenciaApiViewModel(
        flTransfer=False, idMemberTransfer=789, idMemberMembershipTransfer=101
    )

    assert dados_contrato_trasnferencia_api_view_model == same_model
    assert dados_contrato_trasnferencia_api_view_model != different_model
    assert dados_contrato_trasnferencia_api_view_model != 1
