# coding: utf-8

"""
    EVO API

    Use the DNS of your gym as the User and the Secret Key as the password.The authentication method used in the integration is Basic Authentication  # noqa: E501

    OpenAPI spec version: v1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import evo_client
from evo_client.models.clientes_ativos_view_model import (
    ClientesAtivosViewModel,
)  # noqa: E501
from evo_client.rest import ApiException


class TestClientesAtivosViewModel(unittest.TestCase):
    """ClientesAtivosViewModel unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testClientesAtivosViewModel(self):
        """Test ClientesAtivosViewModel"""
        # FIXME: construct object with mandatory attributes with example values
        # model = evo_client.models.clientes_ativos_view_model.ClientesAtivosViewModel()  # noqa: E501
        pass


if __name__ == "__main__":
    unittest.main()
