# coding: utf-8

"""
    EVO API

    Use the DNS of your gym as the User and the Secret Key as the password.The authentication method used in the integration is Basic Authentication  # noqa: E501

    OpenAPI spec version: v1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import pytest

from evo_client.models.atividade_lugar_reserva_api_view_model import (
    AtividadeLugarReservaApiViewModel,
)


@pytest.fixture
def atividade_lugar_reserva_api_view_model():
    return AtividadeLugarReservaApiViewModel(
        number=1, available=True, nameSpot="Spot A"
    )


def test_atividade_lugar_reserva_api_view_model_creation(
    atividade_lugar_reserva_api_view_model,
):
    """Test creating an AtividadeLugarReservaApiViewModel instance"""
    assert isinstance(
        atividade_lugar_reserva_api_view_model, AtividadeLugarReservaApiViewModel
    )
    assert atividade_lugar_reserva_api_view_model.number == 1
    assert atividade_lugar_reserva_api_view_model.available is True
    assert atividade_lugar_reserva_api_view_model.name_spot == "Spot A"


def test_atividade_lugar_reserva_api_view_model_to_dict(
    atividade_lugar_reserva_api_view_model,
):
    """Test converting AtividadeLugarReservaApiViewModel to dictionary"""
    model_dict = atividade_lugar_reserva_api_view_model.to_dict()

    assert isinstance(model_dict, dict)
    assert model_dict["number"] == 1
    assert model_dict["available"] is True
    assert model_dict["nameSpot"] == "Spot A"


def test_atividade_lugar_reserva_api_view_model_equality(
    atividade_lugar_reserva_api_view_model,
):
    """Test equality comparison of AtividadeLugarReservaApiViewModel instances"""
    same_model = AtividadeLugarReservaApiViewModel(
        number=1, available=True, nameSpot="Spot A"
    )

    different_model = AtividadeLugarReservaApiViewModel(
        number=2, available=False, nameSpot="Spot B"
    )

    assert atividade_lugar_reserva_api_view_model == same_model
    assert atividade_lugar_reserva_api_view_model != different_model
    assert atividade_lugar_reserva_api_view_model != 1
