# coding: utf-8

"""
    EVO API

    Use the DNS of your gym as the User and the Secret Key as the password.The authentication method used in the integration is Basic Authentication  # noqa: E501

    OpenAPI spec version: v1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class ClienteTransferenciaViewModel(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'id_cliente': 'int',
        'id_filial_destino': 'int',
        'id_branch_token': 'str',
        'id_consultor_destino': 'int',
        'id_professor_destino': 'int'
    }

    attribute_map = {
        'id_cliente': 'idCliente',
        'id_filial_destino': 'idFilialDestino',
        'id_branch_token': 'idBranchToken',
        'id_consultor_destino': 'idConsultorDestino',
        'id_professor_destino': 'idProfessorDestino'
    }

    def __init__(self, id_cliente=None, id_filial_destino=None, id_branch_token=None, id_consultor_destino=None, id_professor_destino=None):  # noqa: E501
        """ClienteTransferenciaViewModel - a model defined in Swagger"""  # noqa: E501
        self._id_cliente = None
        self._id_filial_destino = None
        self._id_branch_token = None
        self._id_consultor_destino = None
        self._id_professor_destino = None
        self.discriminator = None
        if id_cliente is not None:
            self.id_cliente = id_cliente
        if id_filial_destino is not None:
            self.id_filial_destino = id_filial_destino
        if id_branch_token is not None:
            self.id_branch_token = id_branch_token
        if id_consultor_destino is not None:
            self.id_consultor_destino = id_consultor_destino
        if id_professor_destino is not None:
            self.id_professor_destino = id_professor_destino

    @property
    def id_cliente(self):
        """Gets the id_cliente of this ClienteTransferenciaViewModel.  # noqa: E501


        :return: The id_cliente of this ClienteTransferenciaViewModel.  # noqa: E501
        :rtype: int
        """
        return self._id_cliente

    @id_cliente.setter
    def id_cliente(self, id_cliente):
        """Sets the id_cliente of this ClienteTransferenciaViewModel.


        :param id_cliente: The id_cliente of this ClienteTransferenciaViewModel.  # noqa: E501
        :type: int
        """

        self._id_cliente = id_cliente

    @property
    def id_filial_destino(self):
        """Gets the id_filial_destino of this ClienteTransferenciaViewModel.  # noqa: E501


        :return: The id_filial_destino of this ClienteTransferenciaViewModel.  # noqa: E501
        :rtype: int
        """
        return self._id_filial_destino

    @id_filial_destino.setter
    def id_filial_destino(self, id_filial_destino):
        """Sets the id_filial_destino of this ClienteTransferenciaViewModel.


        :param id_filial_destino: The id_filial_destino of this ClienteTransferenciaViewModel.  # noqa: E501
        :type: int
        """

        self._id_filial_destino = id_filial_destino

    @property
    def id_branch_token(self):
        """Gets the id_branch_token of this ClienteTransferenciaViewModel.  # noqa: E501


        :return: The id_branch_token of this ClienteTransferenciaViewModel.  # noqa: E501
        :rtype: str
        """
        return self._id_branch_token

    @id_branch_token.setter
    def id_branch_token(self, id_branch_token):
        """Sets the id_branch_token of this ClienteTransferenciaViewModel.


        :param id_branch_token: The id_branch_token of this ClienteTransferenciaViewModel.  # noqa: E501
        :type: str
        """

        self._id_branch_token = id_branch_token

    @property
    def id_consultor_destino(self):
        """Gets the id_consultor_destino of this ClienteTransferenciaViewModel.  # noqa: E501


        :return: The id_consultor_destino of this ClienteTransferenciaViewModel.  # noqa: E501
        :rtype: int
        """
        return self._id_consultor_destino

    @id_consultor_destino.setter
    def id_consultor_destino(self, id_consultor_destino):
        """Sets the id_consultor_destino of this ClienteTransferenciaViewModel.


        :param id_consultor_destino: The id_consultor_destino of this ClienteTransferenciaViewModel.  # noqa: E501
        :type: int
        """

        self._id_consultor_destino = id_consultor_destino

    @property
    def id_professor_destino(self):
        """Gets the id_professor_destino of this ClienteTransferenciaViewModel.  # noqa: E501


        :return: The id_professor_destino of this ClienteTransferenciaViewModel.  # noqa: E501
        :rtype: int
        """
        return self._id_professor_destino

    @id_professor_destino.setter
    def id_professor_destino(self, id_professor_destino):
        """Sets the id_professor_destino of this ClienteTransferenciaViewModel.


        :param id_professor_destino: The id_professor_destino of this ClienteTransferenciaViewModel.  # noqa: E501
        :type: int
        """

        self._id_professor_destino = id_professor_destino

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(ClienteTransferenciaViewModel, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, ClienteTransferenciaViewModel):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
