# coding: utf-8

"""
    EVO API

    Use the DNS of your gym as the User and the Secret Key as the password.The authentication method used in the integration is Basic Authentication  # noqa: E501

    OpenAPI spec version: v1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class DadosTrocaContratoApiViewModel(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'fl_membership_swapped': 'bool',
        'id_member_membership_source': 'int'
    }

    attribute_map = {
        'fl_membership_swapped': 'flMembershipSwapped',
        'id_member_membership_source': 'idMemberMembershipSource'
    }

    def __init__(self, fl_membership_swapped=None, id_member_membership_source=None):  # noqa: E501
        """DadosTrocaContratoApiViewModel - a model defined in Swagger"""  # noqa: E501
        self._fl_membership_swapped = None
        self._id_member_membership_source = None
        self.discriminator = None
        if fl_membership_swapped is not None:
            self.fl_membership_swapped = fl_membership_swapped
        if id_member_membership_source is not None:
            self.id_member_membership_source = id_member_membership_source

    @property
    def fl_membership_swapped(self):
        """Gets the fl_membership_swapped of this DadosTrocaContratoApiViewModel.  # noqa: E501


        :return: The fl_membership_swapped of this DadosTrocaContratoApiViewModel.  # noqa: E501
        :rtype: bool
        """
        return self._fl_membership_swapped

    @fl_membership_swapped.setter
    def fl_membership_swapped(self, fl_membership_swapped):
        """Sets the fl_membership_swapped of this DadosTrocaContratoApiViewModel.


        :param fl_membership_swapped: The fl_membership_swapped of this DadosTrocaContratoApiViewModel.  # noqa: E501
        :type: bool
        """

        self._fl_membership_swapped = fl_membership_swapped

    @property
    def id_member_membership_source(self):
        """Gets the id_member_membership_source of this DadosTrocaContratoApiViewModel.  # noqa: E501


        :return: The id_member_membership_source of this DadosTrocaContratoApiViewModel.  # noqa: E501
        :rtype: int
        """
        return self._id_member_membership_source

    @id_member_membership_source.setter
    def id_member_membership_source(self, id_member_membership_source):
        """Sets the id_member_membership_source of this DadosTrocaContratoApiViewModel.


        :param id_member_membership_source: The id_member_membership_source of this DadosTrocaContratoApiViewModel.  # noqa: E501
        :type: int
        """

        self._id_member_membership_source = id_member_membership_source

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(DadosTrocaContratoApiViewModel, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, DadosTrocaContratoApiViewModel):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
