# coding: utf-8

"""
    EVO API

    Use the DNS of your gym as the User and the Secret Key as the password.The authentication method used in the integration is Basic Authentication  # noqa: E501

    OpenAPI spec version: v1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class MemberServiceViewModel(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'id_service': 'int',
        'name_service': 'str'
    }

    attribute_map = {
        'id_service': 'idService',
        'name_service': 'nameService'
    }

    def __init__(self, id_service=None, name_service=None):  # noqa: E501
        """MemberServiceViewModel - a model defined in Swagger"""  # noqa: E501
        self._id_service = None
        self._name_service = None
        self.discriminator = None
        if id_service is not None:
            self.id_service = id_service
        if name_service is not None:
            self.name_service = name_service

    @property
    def id_service(self):
        """Gets the id_service of this MemberServiceViewModel.  # noqa: E501


        :return: The id_service of this MemberServiceViewModel.  # noqa: E501
        :rtype: int
        """
        return self._id_service

    @id_service.setter
    def id_service(self, id_service):
        """Sets the id_service of this MemberServiceViewModel.


        :param id_service: The id_service of this MemberServiceViewModel.  # noqa: E501
        :type: int
        """

        self._id_service = id_service

    @property
    def name_service(self):
        """Gets the name_service of this MemberServiceViewModel.  # noqa: E501


        :return: The name_service of this MemberServiceViewModel.  # noqa: E501
        :rtype: str
        """
        return self._name_service

    @name_service.setter
    def name_service(self, name_service):
        """Sets the name_service of this MemberServiceViewModel.


        :param name_service: The name_service of this MemberServiceViewModel.  # noqa: E501
        :type: str
        """

        self._name_service = name_service

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(MemberServiceViewModel, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, MemberServiceViewModel):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
