# coding: utf-8

"""
    EVO API

    Use the DNS of your gym as the User and the Secret Key as the password.The authentication method used in the integration is Basic Authentication  # noqa: E501

    OpenAPI spec version: v1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class MemberNewSaleViewModel(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'id_member': 'int',
        'document': 'str',
        'zip_code': 'str',
        'address': 'str',
        'number': 'str',
        'complement': 'str',
        'neighborhood': 'str',
        'city': 'str',
        'id_state': 'int'
    }

    attribute_map = {
        'id_member': 'idMember',
        'document': 'document',
        'zip_code': 'zipCode',
        'address': 'address',
        'number': 'number',
        'complement': 'complement',
        'neighborhood': 'neighborhood',
        'city': 'city',
        'id_state': 'idState'
    }

    def __init__(self, id_member=None, document=None, zip_code=None, address=None, number=None, complement=None, neighborhood=None, city=None, id_state=None):  # noqa: E501
        """MemberNewSaleViewModel - a model defined in Swagger"""  # noqa: E501
        self._id_member = None
        self._document = None
        self._zip_code = None
        self._address = None
        self._number = None
        self._complement = None
        self._neighborhood = None
        self._city = None
        self._id_state = None
        self.discriminator = None
        if id_member is not None:
            self.id_member = id_member
        if document is not None:
            self.document = document
        if zip_code is not None:
            self.zip_code = zip_code
        if address is not None:
            self.address = address
        if number is not None:
            self.number = number
        if complement is not None:
            self.complement = complement
        if neighborhood is not None:
            self.neighborhood = neighborhood
        if city is not None:
            self.city = city
        if id_state is not None:
            self.id_state = id_state

    @property
    def id_member(self):
        """Gets the id_member of this MemberNewSaleViewModel.  # noqa: E501


        :return: The id_member of this MemberNewSaleViewModel.  # noqa: E501
        :rtype: int
        """
        return self._id_member

    @id_member.setter
    def id_member(self, id_member):
        """Sets the id_member of this MemberNewSaleViewModel.


        :param id_member: The id_member of this MemberNewSaleViewModel.  # noqa: E501
        :type: int
        """

        self._id_member = id_member

    @property
    def document(self):
        """Gets the document of this MemberNewSaleViewModel.  # noqa: E501


        :return: The document of this MemberNewSaleViewModel.  # noqa: E501
        :rtype: str
        """
        return self._document

    @document.setter
    def document(self, document):
        """Sets the document of this MemberNewSaleViewModel.


        :param document: The document of this MemberNewSaleViewModel.  # noqa: E501
        :type: str
        """

        self._document = document

    @property
    def zip_code(self):
        """Gets the zip_code of this MemberNewSaleViewModel.  # noqa: E501


        :return: The zip_code of this MemberNewSaleViewModel.  # noqa: E501
        :rtype: str
        """
        return self._zip_code

    @zip_code.setter
    def zip_code(self, zip_code):
        """Sets the zip_code of this MemberNewSaleViewModel.


        :param zip_code: The zip_code of this MemberNewSaleViewModel.  # noqa: E501
        :type: str
        """

        self._zip_code = zip_code

    @property
    def address(self):
        """Gets the address of this MemberNewSaleViewModel.  # noqa: E501


        :return: The address of this MemberNewSaleViewModel.  # noqa: E501
        :rtype: str
        """
        return self._address

    @address.setter
    def address(self, address):
        """Sets the address of this MemberNewSaleViewModel.


        :param address: The address of this MemberNewSaleViewModel.  # noqa: E501
        :type: str
        """

        self._address = address

    @property
    def number(self):
        """Gets the number of this MemberNewSaleViewModel.  # noqa: E501


        :return: The number of this MemberNewSaleViewModel.  # noqa: E501
        :rtype: str
        """
        return self._number

    @number.setter
    def number(self, number):
        """Sets the number of this MemberNewSaleViewModel.


        :param number: The number of this MemberNewSaleViewModel.  # noqa: E501
        :type: str
        """

        self._number = number

    @property
    def complement(self):
        """Gets the complement of this MemberNewSaleViewModel.  # noqa: E501


        :return: The complement of this MemberNewSaleViewModel.  # noqa: E501
        :rtype: str
        """
        return self._complement

    @complement.setter
    def complement(self, complement):
        """Sets the complement of this MemberNewSaleViewModel.


        :param complement: The complement of this MemberNewSaleViewModel.  # noqa: E501
        :type: str
        """

        self._complement = complement

    @property
    def neighborhood(self):
        """Gets the neighborhood of this MemberNewSaleViewModel.  # noqa: E501


        :return: The neighborhood of this MemberNewSaleViewModel.  # noqa: E501
        :rtype: str
        """
        return self._neighborhood

    @neighborhood.setter
    def neighborhood(self, neighborhood):
        """Sets the neighborhood of this MemberNewSaleViewModel.


        :param neighborhood: The neighborhood of this MemberNewSaleViewModel.  # noqa: E501
        :type: str
        """

        self._neighborhood = neighborhood

    @property
    def city(self):
        """Gets the city of this MemberNewSaleViewModel.  # noqa: E501


        :return: The city of this MemberNewSaleViewModel.  # noqa: E501
        :rtype: str
        """
        return self._city

    @city.setter
    def city(self, city):
        """Sets the city of this MemberNewSaleViewModel.


        :param city: The city of this MemberNewSaleViewModel.  # noqa: E501
        :type: str
        """

        self._city = city

    @property
    def id_state(self):
        """Gets the id_state of this MemberNewSaleViewModel.  # noqa: E501


        :return: The id_state of this MemberNewSaleViewModel.  # noqa: E501
        :rtype: int
        """
        return self._id_state

    @id_state.setter
    def id_state(self, id_state):
        """Sets the id_state of this MemberNewSaleViewModel.


        :param id_state: The id_state of this MemberNewSaleViewModel.  # noqa: E501
        :type: int
        """

        self._id_state = id_state

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(MemberNewSaleViewModel, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, MemberNewSaleViewModel):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
