# coding: utf-8

"""
    EVO API

    Use the DNS of your gym as the User and the Secret Key as the password.The authentication method used in the integration is Basic Authentication  # noqa: E501

    OpenAPI spec version: v1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class MembersApiViewModel(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'id_member': 'int',
        'first_name': 'str',
        'last_name': 'str',
        'register_date': 'datetime',
        'id_branch': 'int',
        'branch_name': 'str',
        'access_blocked': 'bool',
        'blocked_reason': 'str',
        'document': 'str',
        'document_id': 'str',
        'marital_status': 'str',
        'gender': 'str',
        'birth_date': 'datetime',
        'address': 'str',
        'state': 'str',
        'city': 'str',
        'zip_code': 'str',
        'complement': 'str',
        'neighborhood': 'str',
        'access_card_number': 'str',
        'number': 'str',
        'cpf': 'str',
        'passport': 'str',
        'membership_status': 'str',
        'penalized': 'bool',
        'status': 'str',
        'contacts': 'list[TelefoneApiViewModel]',
        'memberships': 'list[MemberMembershipApiViewModel]',
        'last_access_date': 'datetime',
        'conversion_date': 'datetime',
        'id_employee_consultant': 'int',
        'name_employee_consultant': 'str',
        'id_employee_instructor': 'int',
        'name_employee_instructor': 'str',
        'id_employee_personal_trainer': 'int',
        'name_employee_personal_trainer': 'str',
        'photo_url': 'str',
        'country': 'str',
        'id_member_migration': 'str',
        'responsibles': 'list[MemberResponsibleViewModel]',
        'gympass_id': 'str',
        'personal_trainer': 'bool',
        'personal_type': 'str',
        'cref': 'str',
        'cref_expiration_date': 'datetime'
    }

    attribute_map = {
        'id_member': 'idMember',
        'first_name': 'firstName',
        'last_name': 'lastName',
        'register_date': 'registerDate',
        'id_branch': 'idBranch',
        'branch_name': 'branchName',
        'access_blocked': 'accessBlocked',
        'blocked_reason': 'blockedReason',
        'document': 'document',
        'document_id': 'documentId',
        'marital_status': 'maritalStatus',
        'gender': 'gender',
        'birth_date': 'birthDate',
        'address': 'address',
        'state': 'state',
        'city': 'city',
        'zip_code': 'zipCode',
        'complement': 'complement',
        'neighborhood': 'neighborhood',
        'access_card_number': 'accessCardNumber',
        'number': 'number',
        'cpf': 'cpf',
        'passport': 'passport',
        'membership_status': 'membershipStatus',
        'penalized': 'penalized',
        'status': 'status',
        'contacts': 'contacts',
        'memberships': 'memberships',
        'last_access_date': 'lastAccessDate',
        'conversion_date': 'conversionDate',
        'id_employee_consultant': 'idEmployeeConsultant',
        'name_employee_consultant': 'nameEmployeeConsultant',
        'id_employee_instructor': 'idEmployeeInstructor',
        'name_employee_instructor': 'nameEmployeeInstructor',
        'id_employee_personal_trainer': 'idEmployeePersonalTrainer',
        'name_employee_personal_trainer': 'nameEmployeePersonalTrainer',
        'photo_url': 'photoUrl',
        'country': 'country',
        'id_member_migration': 'idMemberMigration',
        'responsibles': 'responsibles',
        'gympass_id': 'gympassId',
        'personal_trainer': 'personalTrainer',
        'personal_type': 'personalType',
        'cref': 'cref',
        'cref_expiration_date': 'crefExpirationDate'
    }

    def __init__(self, id_member=None, first_name=None, last_name=None, register_date=None, id_branch=None, branch_name=None, access_blocked=None, blocked_reason=None, document=None, document_id=None, marital_status=None, gender=None, birth_date=None, address=None, state=None, city=None, zip_code=None, complement=None, neighborhood=None, access_card_number=None, number=None, cpf=None, passport=None, membership_status=None, penalized=None, status=None, contacts=None, memberships=None, last_access_date=None, conversion_date=None, id_employee_consultant=None, name_employee_consultant=None, id_employee_instructor=None, name_employee_instructor=None, id_employee_personal_trainer=None, name_employee_personal_trainer=None, photo_url=None, country=None, id_member_migration=None, responsibles=None, gympass_id=None, personal_trainer=None, personal_type=None, cref=None, cref_expiration_date=None):  # noqa: E501
        """MembersApiViewModel - a model defined in Swagger"""  # noqa: E501
        self._id_member = None
        self._first_name = None
        self._last_name = None
        self._register_date = None
        self._id_branch = None
        self._branch_name = None
        self._access_blocked = None
        self._blocked_reason = None
        self._document = None
        self._document_id = None
        self._marital_status = None
        self._gender = None
        self._birth_date = None
        self._address = None
        self._state = None
        self._city = None
        self._zip_code = None
        self._complement = None
        self._neighborhood = None
        self._access_card_number = None
        self._number = None
        self._cpf = None
        self._passport = None
        self._membership_status = None
        self._penalized = None
        self._status = None
        self._contacts = None
        self._memberships = None
        self._last_access_date = None
        self._conversion_date = None
        self._id_employee_consultant = None
        self._name_employee_consultant = None
        self._id_employee_instructor = None
        self._name_employee_instructor = None
        self._id_employee_personal_trainer = None
        self._name_employee_personal_trainer = None
        self._photo_url = None
        self._country = None
        self._id_member_migration = None
        self._responsibles = None
        self._gympass_id = None
        self._personal_trainer = None
        self._personal_type = None
        self._cref = None
        self._cref_expiration_date = None
        self.discriminator = None
        if id_member is not None:
            self.id_member = id_member
        if first_name is not None:
            self.first_name = first_name
        if last_name is not None:
            self.last_name = last_name
        if register_date is not None:
            self.register_date = register_date
        if id_branch is not None:
            self.id_branch = id_branch
        if branch_name is not None:
            self.branch_name = branch_name
        if access_blocked is not None:
            self.access_blocked = access_blocked
        if blocked_reason is not None:
            self.blocked_reason = blocked_reason
        if document is not None:
            self.document = document
        if document_id is not None:
            self.document_id = document_id
        if marital_status is not None:
            self.marital_status = marital_status
        if gender is not None:
            self.gender = gender
        if birth_date is not None:
            self.birth_date = birth_date
        if address is not None:
            self.address = address
        if state is not None:
            self.state = state
        if city is not None:
            self.city = city
        if zip_code is not None:
            self.zip_code = zip_code
        if complement is not None:
            self.complement = complement
        if neighborhood is not None:
            self.neighborhood = neighborhood
        if access_card_number is not None:
            self.access_card_number = access_card_number
        if number is not None:
            self.number = number
        if cpf is not None:
            self.cpf = cpf
        if passport is not None:
            self.passport = passport
        if membership_status is not None:
            self.membership_status = membership_status
        if penalized is not None:
            self.penalized = penalized
        if status is not None:
            self.status = status
        if contacts is not None:
            self.contacts = contacts
        if memberships is not None:
            self.memberships = memberships
        if last_access_date is not None:
            self.last_access_date = last_access_date
        if conversion_date is not None:
            self.conversion_date = conversion_date
        if id_employee_consultant is not None:
            self.id_employee_consultant = id_employee_consultant
        if name_employee_consultant is not None:
            self.name_employee_consultant = name_employee_consultant
        if id_employee_instructor is not None:
            self.id_employee_instructor = id_employee_instructor
        if name_employee_instructor is not None:
            self.name_employee_instructor = name_employee_instructor
        if id_employee_personal_trainer is not None:
            self.id_employee_personal_trainer = id_employee_personal_trainer
        if name_employee_personal_trainer is not None:
            self.name_employee_personal_trainer = name_employee_personal_trainer
        if photo_url is not None:
            self.photo_url = photo_url
        if country is not None:
            self.country = country
        if id_member_migration is not None:
            self.id_member_migration = id_member_migration
        if responsibles is not None:
            self.responsibles = responsibles
        if gympass_id is not None:
            self.gympass_id = gympass_id
        if personal_trainer is not None:
            self.personal_trainer = personal_trainer
        if personal_type is not None:
            self.personal_type = personal_type
        if cref is not None:
            self.cref = cref
        if cref_expiration_date is not None:
            self.cref_expiration_date = cref_expiration_date

    @property
    def id_member(self):
        """Gets the id_member of this MembersApiViewModel.  # noqa: E501


        :return: The id_member of this MembersApiViewModel.  # noqa: E501
        :rtype: int
        """
        return self._id_member

    @id_member.setter
    def id_member(self, id_member):
        """Sets the id_member of this MembersApiViewModel.


        :param id_member: The id_member of this MembersApiViewModel.  # noqa: E501
        :type: int
        """

        self._id_member = id_member

    @property
    def first_name(self):
        """Gets the first_name of this MembersApiViewModel.  # noqa: E501


        :return: The first_name of this MembersApiViewModel.  # noqa: E501
        :rtype: str
        """
        return self._first_name

    @first_name.setter
    def first_name(self, first_name):
        """Sets the first_name of this MembersApiViewModel.


        :param first_name: The first_name of this MembersApiViewModel.  # noqa: E501
        :type: str
        """

        self._first_name = first_name

    @property
    def last_name(self):
        """Gets the last_name of this MembersApiViewModel.  # noqa: E501


        :return: The last_name of this MembersApiViewModel.  # noqa: E501
        :rtype: str
        """
        return self._last_name

    @last_name.setter
    def last_name(self, last_name):
        """Sets the last_name of this MembersApiViewModel.


        :param last_name: The last_name of this MembersApiViewModel.  # noqa: E501
        :type: str
        """

        self._last_name = last_name

    @property
    def register_date(self):
        """Gets the register_date of this MembersApiViewModel.  # noqa: E501


        :return: The register_date of this MembersApiViewModel.  # noqa: E501
        :rtype: datetime
        """
        return self._register_date

    @register_date.setter
    def register_date(self, register_date):
        """Sets the register_date of this MembersApiViewModel.


        :param register_date: The register_date of this MembersApiViewModel.  # noqa: E501
        :type: datetime
        """

        self._register_date = register_date

    @property
    def id_branch(self):
        """Gets the id_branch of this MembersApiViewModel.  # noqa: E501


        :return: The id_branch of this MembersApiViewModel.  # noqa: E501
        :rtype: int
        """
        return self._id_branch

    @id_branch.setter
    def id_branch(self, id_branch):
        """Sets the id_branch of this MembersApiViewModel.


        :param id_branch: The id_branch of this MembersApiViewModel.  # noqa: E501
        :type: int
        """

        self._id_branch = id_branch

    @property
    def branch_name(self):
        """Gets the branch_name of this MembersApiViewModel.  # noqa: E501


        :return: The branch_name of this MembersApiViewModel.  # noqa: E501
        :rtype: str
        """
        return self._branch_name

    @branch_name.setter
    def branch_name(self, branch_name):
        """Sets the branch_name of this MembersApiViewModel.


        :param branch_name: The branch_name of this MembersApiViewModel.  # noqa: E501
        :type: str
        """

        self._branch_name = branch_name

    @property
    def access_blocked(self):
        """Gets the access_blocked of this MembersApiViewModel.  # noqa: E501


        :return: The access_blocked of this MembersApiViewModel.  # noqa: E501
        :rtype: bool
        """
        return self._access_blocked

    @access_blocked.setter
    def access_blocked(self, access_blocked):
        """Sets the access_blocked of this MembersApiViewModel.


        :param access_blocked: The access_blocked of this MembersApiViewModel.  # noqa: E501
        :type: bool
        """

        self._access_blocked = access_blocked

    @property
    def blocked_reason(self):
        """Gets the blocked_reason of this MembersApiViewModel.  # noqa: E501


        :return: The blocked_reason of this MembersApiViewModel.  # noqa: E501
        :rtype: str
        """
        return self._blocked_reason

    @blocked_reason.setter
    def blocked_reason(self, blocked_reason):
        """Sets the blocked_reason of this MembersApiViewModel.


        :param blocked_reason: The blocked_reason of this MembersApiViewModel.  # noqa: E501
        :type: str
        """

        self._blocked_reason = blocked_reason

    @property
    def document(self):
        """Gets the document of this MembersApiViewModel.  # noqa: E501


        :return: The document of this MembersApiViewModel.  # noqa: E501
        :rtype: str
        """
        return self._document

    @document.setter
    def document(self, document):
        """Sets the document of this MembersApiViewModel.


        :param document: The document of this MembersApiViewModel.  # noqa: E501
        :type: str
        """

        self._document = document

    @property
    def document_id(self):
        """Gets the document_id of this MembersApiViewModel.  # noqa: E501


        :return: The document_id of this MembersApiViewModel.  # noqa: E501
        :rtype: str
        """
        return self._document_id

    @document_id.setter
    def document_id(self, document_id):
        """Sets the document_id of this MembersApiViewModel.


        :param document_id: The document_id of this MembersApiViewModel.  # noqa: E501
        :type: str
        """

        self._document_id = document_id

    @property
    def marital_status(self):
        """Gets the marital_status of this MembersApiViewModel.  # noqa: E501


        :return: The marital_status of this MembersApiViewModel.  # noqa: E501
        :rtype: str
        """
        return self._marital_status

    @marital_status.setter
    def marital_status(self, marital_status):
        """Sets the marital_status of this MembersApiViewModel.


        :param marital_status: The marital_status of this MembersApiViewModel.  # noqa: E501
        :type: str
        """

        self._marital_status = marital_status

    @property
    def gender(self):
        """Gets the gender of this MembersApiViewModel.  # noqa: E501


        :return: The gender of this MembersApiViewModel.  # noqa: E501
        :rtype: str
        """
        return self._gender

    @gender.setter
    def gender(self, gender):
        """Sets the gender of this MembersApiViewModel.


        :param gender: The gender of this MembersApiViewModel.  # noqa: E501
        :type: str
        """

        self._gender = gender

    @property
    def birth_date(self):
        """Gets the birth_date of this MembersApiViewModel.  # noqa: E501


        :return: The birth_date of this MembersApiViewModel.  # noqa: E501
        :rtype: datetime
        """
        return self._birth_date

    @birth_date.setter
    def birth_date(self, birth_date):
        """Sets the birth_date of this MembersApiViewModel.


        :param birth_date: The birth_date of this MembersApiViewModel.  # noqa: E501
        :type: datetime
        """

        self._birth_date = birth_date

    @property
    def address(self):
        """Gets the address of this MembersApiViewModel.  # noqa: E501


        :return: The address of this MembersApiViewModel.  # noqa: E501
        :rtype: str
        """
        return self._address

    @address.setter
    def address(self, address):
        """Sets the address of this MembersApiViewModel.


        :param address: The address of this MembersApiViewModel.  # noqa: E501
        :type: str
        """

        self._address = address

    @property
    def state(self):
        """Gets the state of this MembersApiViewModel.  # noqa: E501


        :return: The state of this MembersApiViewModel.  # noqa: E501
        :rtype: str
        """
        return self._state

    @state.setter
    def state(self, state):
        """Sets the state of this MembersApiViewModel.


        :param state: The state of this MembersApiViewModel.  # noqa: E501
        :type: str
        """

        self._state = state

    @property
    def city(self):
        """Gets the city of this MembersApiViewModel.  # noqa: E501


        :return: The city of this MembersApiViewModel.  # noqa: E501
        :rtype: str
        """
        return self._city

    @city.setter
    def city(self, city):
        """Sets the city of this MembersApiViewModel.


        :param city: The city of this MembersApiViewModel.  # noqa: E501
        :type: str
        """

        self._city = city

    @property
    def zip_code(self):
        """Gets the zip_code of this MembersApiViewModel.  # noqa: E501


        :return: The zip_code of this MembersApiViewModel.  # noqa: E501
        :rtype: str
        """
        return self._zip_code

    @zip_code.setter
    def zip_code(self, zip_code):
        """Sets the zip_code of this MembersApiViewModel.


        :param zip_code: The zip_code of this MembersApiViewModel.  # noqa: E501
        :type: str
        """

        self._zip_code = zip_code

    @property
    def complement(self):
        """Gets the complement of this MembersApiViewModel.  # noqa: E501


        :return: The complement of this MembersApiViewModel.  # noqa: E501
        :rtype: str
        """
        return self._complement

    @complement.setter
    def complement(self, complement):
        """Sets the complement of this MembersApiViewModel.


        :param complement: The complement of this MembersApiViewModel.  # noqa: E501
        :type: str
        """

        self._complement = complement

    @property
    def neighborhood(self):
        """Gets the neighborhood of this MembersApiViewModel.  # noqa: E501


        :return: The neighborhood of this MembersApiViewModel.  # noqa: E501
        :rtype: str
        """
        return self._neighborhood

    @neighborhood.setter
    def neighborhood(self, neighborhood):
        """Sets the neighborhood of this MembersApiViewModel.


        :param neighborhood: The neighborhood of this MembersApiViewModel.  # noqa: E501
        :type: str
        """

        self._neighborhood = neighborhood

    @property
    def access_card_number(self):
        """Gets the access_card_number of this MembersApiViewModel.  # noqa: E501


        :return: The access_card_number of this MembersApiViewModel.  # noqa: E501
        :rtype: str
        """
        return self._access_card_number

    @access_card_number.setter
    def access_card_number(self, access_card_number):
        """Sets the access_card_number of this MembersApiViewModel.


        :param access_card_number: The access_card_number of this MembersApiViewModel.  # noqa: E501
        :type: str
        """

        self._access_card_number = access_card_number

    @property
    def number(self):
        """Gets the number of this MembersApiViewModel.  # noqa: E501


        :return: The number of this MembersApiViewModel.  # noqa: E501
        :rtype: str
        """
        return self._number

    @number.setter
    def number(self, number):
        """Sets the number of this MembersApiViewModel.


        :param number: The number of this MembersApiViewModel.  # noqa: E501
        :type: str
        """

        self._number = number

    @property
    def cpf(self):
        """Gets the cpf of this MembersApiViewModel.  # noqa: E501


        :return: The cpf of this MembersApiViewModel.  # noqa: E501
        :rtype: str
        """
        return self._cpf

    @cpf.setter
    def cpf(self, cpf):
        """Sets the cpf of this MembersApiViewModel.


        :param cpf: The cpf of this MembersApiViewModel.  # noqa: E501
        :type: str
        """

        self._cpf = cpf

    @property
    def passport(self):
        """Gets the passport of this MembersApiViewModel.  # noqa: E501


        :return: The passport of this MembersApiViewModel.  # noqa: E501
        :rtype: str
        """
        return self._passport

    @passport.setter
    def passport(self, passport):
        """Sets the passport of this MembersApiViewModel.


        :param passport: The passport of this MembersApiViewModel.  # noqa: E501
        :type: str
        """

        self._passport = passport

    @property
    def membership_status(self):
        """Gets the membership_status of this MembersApiViewModel.  # noqa: E501


        :return: The membership_status of this MembersApiViewModel.  # noqa: E501
        :rtype: str
        """
        return self._membership_status

    @membership_status.setter
    def membership_status(self, membership_status):
        """Sets the membership_status of this MembersApiViewModel.


        :param membership_status: The membership_status of this MembersApiViewModel.  # noqa: E501
        :type: str
        """

        self._membership_status = membership_status

    @property
    def penalized(self):
        """Gets the penalized of this MembersApiViewModel.  # noqa: E501


        :return: The penalized of this MembersApiViewModel.  # noqa: E501
        :rtype: bool
        """
        return self._penalized

    @penalized.setter
    def penalized(self, penalized):
        """Sets the penalized of this MembersApiViewModel.


        :param penalized: The penalized of this MembersApiViewModel.  # noqa: E501
        :type: bool
        """

        self._penalized = penalized

    @property
    def status(self):
        """Gets the status of this MembersApiViewModel.  # noqa: E501


        :return: The status of this MembersApiViewModel.  # noqa: E501
        :rtype: str
        """
        return self._status

    @status.setter
    def status(self, status):
        """Sets the status of this MembersApiViewModel.


        :param status: The status of this MembersApiViewModel.  # noqa: E501
        :type: str
        """

        self._status = status

    @property
    def contacts(self):
        """Gets the contacts of this MembersApiViewModel.  # noqa: E501


        :return: The contacts of this MembersApiViewModel.  # noqa: E501
        :rtype: list[TelefoneApiViewModel]
        """
        return self._contacts

    @contacts.setter
    def contacts(self, contacts):
        """Sets the contacts of this MembersApiViewModel.


        :param contacts: The contacts of this MembersApiViewModel.  # noqa: E501
        :type: list[TelefoneApiViewModel]
        """

        self._contacts = contacts

    @property
    def memberships(self):
        """Gets the memberships of this MembersApiViewModel.  # noqa: E501


        :return: The memberships of this MembersApiViewModel.  # noqa: E501
        :rtype: list[MemberMembershipApiViewModel]
        """
        return self._memberships

    @memberships.setter
    def memberships(self, memberships):
        """Sets the memberships of this MembersApiViewModel.


        :param memberships: The memberships of this MembersApiViewModel.  # noqa: E501
        :type: list[MemberMembershipApiViewModel]
        """

        self._memberships = memberships

    @property
    def last_access_date(self):
        """Gets the last_access_date of this MembersApiViewModel.  # noqa: E501


        :return: The last_access_date of this MembersApiViewModel.  # noqa: E501
        :rtype: datetime
        """
        return self._last_access_date

    @last_access_date.setter
    def last_access_date(self, last_access_date):
        """Sets the last_access_date of this MembersApiViewModel.


        :param last_access_date: The last_access_date of this MembersApiViewModel.  # noqa: E501
        :type: datetime
        """

        self._last_access_date = last_access_date

    @property
    def conversion_date(self):
        """Gets the conversion_date of this MembersApiViewModel.  # noqa: E501


        :return: The conversion_date of this MembersApiViewModel.  # noqa: E501
        :rtype: datetime
        """
        return self._conversion_date

    @conversion_date.setter
    def conversion_date(self, conversion_date):
        """Sets the conversion_date of this MembersApiViewModel.


        :param conversion_date: The conversion_date of this MembersApiViewModel.  # noqa: E501
        :type: datetime
        """

        self._conversion_date = conversion_date

    @property
    def id_employee_consultant(self):
        """Gets the id_employee_consultant of this MembersApiViewModel.  # noqa: E501


        :return: The id_employee_consultant of this MembersApiViewModel.  # noqa: E501
        :rtype: int
        """
        return self._id_employee_consultant

    @id_employee_consultant.setter
    def id_employee_consultant(self, id_employee_consultant):
        """Sets the id_employee_consultant of this MembersApiViewModel.


        :param id_employee_consultant: The id_employee_consultant of this MembersApiViewModel.  # noqa: E501
        :type: int
        """

        self._id_employee_consultant = id_employee_consultant

    @property
    def name_employee_consultant(self):
        """Gets the name_employee_consultant of this MembersApiViewModel.  # noqa: E501


        :return: The name_employee_consultant of this MembersApiViewModel.  # noqa: E501
        :rtype: str
        """
        return self._name_employee_consultant

    @name_employee_consultant.setter
    def name_employee_consultant(self, name_employee_consultant):
        """Sets the name_employee_consultant of this MembersApiViewModel.


        :param name_employee_consultant: The name_employee_consultant of this MembersApiViewModel.  # noqa: E501
        :type: str
        """

        self._name_employee_consultant = name_employee_consultant

    @property
    def id_employee_instructor(self):
        """Gets the id_employee_instructor of this MembersApiViewModel.  # noqa: E501


        :return: The id_employee_instructor of this MembersApiViewModel.  # noqa: E501
        :rtype: int
        """
        return self._id_employee_instructor

    @id_employee_instructor.setter
    def id_employee_instructor(self, id_employee_instructor):
        """Sets the id_employee_instructor of this MembersApiViewModel.


        :param id_employee_instructor: The id_employee_instructor of this MembersApiViewModel.  # noqa: E501
        :type: int
        """

        self._id_employee_instructor = id_employee_instructor

    @property
    def name_employee_instructor(self):
        """Gets the name_employee_instructor of this MembersApiViewModel.  # noqa: E501


        :return: The name_employee_instructor of this MembersApiViewModel.  # noqa: E501
        :rtype: str
        """
        return self._name_employee_instructor

    @name_employee_instructor.setter
    def name_employee_instructor(self, name_employee_instructor):
        """Sets the name_employee_instructor of this MembersApiViewModel.


        :param name_employee_instructor: The name_employee_instructor of this MembersApiViewModel.  # noqa: E501
        :type: str
        """

        self._name_employee_instructor = name_employee_instructor

    @property
    def id_employee_personal_trainer(self):
        """Gets the id_employee_personal_trainer of this MembersApiViewModel.  # noqa: E501


        :return: The id_employee_personal_trainer of this MembersApiViewModel.  # noqa: E501
        :rtype: int
        """
        return self._id_employee_personal_trainer

    @id_employee_personal_trainer.setter
    def id_employee_personal_trainer(self, id_employee_personal_trainer):
        """Sets the id_employee_personal_trainer of this MembersApiViewModel.


        :param id_employee_personal_trainer: The id_employee_personal_trainer of this MembersApiViewModel.  # noqa: E501
        :type: int
        """

        self._id_employee_personal_trainer = id_employee_personal_trainer

    @property
    def name_employee_personal_trainer(self):
        """Gets the name_employee_personal_trainer of this MembersApiViewModel.  # noqa: E501


        :return: The name_employee_personal_trainer of this MembersApiViewModel.  # noqa: E501
        :rtype: str
        """
        return self._name_employee_personal_trainer

    @name_employee_personal_trainer.setter
    def name_employee_personal_trainer(self, name_employee_personal_trainer):
        """Sets the name_employee_personal_trainer of this MembersApiViewModel.


        :param name_employee_personal_trainer: The name_employee_personal_trainer of this MembersApiViewModel.  # noqa: E501
        :type: str
        """

        self._name_employee_personal_trainer = name_employee_personal_trainer

    @property
    def photo_url(self):
        """Gets the photo_url of this MembersApiViewModel.  # noqa: E501


        :return: The photo_url of this MembersApiViewModel.  # noqa: E501
        :rtype: str
        """
        return self._photo_url

    @photo_url.setter
    def photo_url(self, photo_url):
        """Sets the photo_url of this MembersApiViewModel.


        :param photo_url: The photo_url of this MembersApiViewModel.  # noqa: E501
        :type: str
        """

        self._photo_url = photo_url

    @property
    def country(self):
        """Gets the country of this MembersApiViewModel.  # noqa: E501


        :return: The country of this MembersApiViewModel.  # noqa: E501
        :rtype: str
        """
        return self._country

    @country.setter
    def country(self, country):
        """Sets the country of this MembersApiViewModel.


        :param country: The country of this MembersApiViewModel.  # noqa: E501
        :type: str
        """

        self._country = country

    @property
    def id_member_migration(self):
        """Gets the id_member_migration of this MembersApiViewModel.  # noqa: E501


        :return: The id_member_migration of this MembersApiViewModel.  # noqa: E501
        :rtype: str
        """
        return self._id_member_migration

    @id_member_migration.setter
    def id_member_migration(self, id_member_migration):
        """Sets the id_member_migration of this MembersApiViewModel.


        :param id_member_migration: The id_member_migration of this MembersApiViewModel.  # noqa: E501
        :type: str
        """

        self._id_member_migration = id_member_migration

    @property
    def responsibles(self):
        """Gets the responsibles of this MembersApiViewModel.  # noqa: E501


        :return: The responsibles of this MembersApiViewModel.  # noqa: E501
        :rtype: list[MemberResponsibleViewModel]
        """
        return self._responsibles

    @responsibles.setter
    def responsibles(self, responsibles):
        """Sets the responsibles of this MembersApiViewModel.


        :param responsibles: The responsibles of this MembersApiViewModel.  # noqa: E501
        :type: list[MemberResponsibleViewModel]
        """

        self._responsibles = responsibles

    @property
    def gympass_id(self):
        """Gets the gympass_id of this MembersApiViewModel.  # noqa: E501


        :return: The gympass_id of this MembersApiViewModel.  # noqa: E501
        :rtype: str
        """
        return self._gympass_id

    @gympass_id.setter
    def gympass_id(self, gympass_id):
        """Sets the gympass_id of this MembersApiViewModel.


        :param gympass_id: The gympass_id of this MembersApiViewModel.  # noqa: E501
        :type: str
        """

        self._gympass_id = gympass_id

    @property
    def personal_trainer(self):
        """Gets the personal_trainer of this MembersApiViewModel.  # noqa: E501


        :return: The personal_trainer of this MembersApiViewModel.  # noqa: E501
        :rtype: bool
        """
        return self._personal_trainer

    @personal_trainer.setter
    def personal_trainer(self, personal_trainer):
        """Sets the personal_trainer of this MembersApiViewModel.


        :param personal_trainer: The personal_trainer of this MembersApiViewModel.  # noqa: E501
        :type: bool
        """

        self._personal_trainer = personal_trainer

    @property
    def personal_type(self):
        """Gets the personal_type of this MembersApiViewModel.  # noqa: E501


        :return: The personal_type of this MembersApiViewModel.  # noqa: E501
        :rtype: str
        """
        return self._personal_type

    @personal_type.setter
    def personal_type(self, personal_type):
        """Sets the personal_type of this MembersApiViewModel.


        :param personal_type: The personal_type of this MembersApiViewModel.  # noqa: E501
        :type: str
        """

        self._personal_type = personal_type

    @property
    def cref(self):
        """Gets the cref of this MembersApiViewModel.  # noqa: E501


        :return: The cref of this MembersApiViewModel.  # noqa: E501
        :rtype: str
        """
        return self._cref

    @cref.setter
    def cref(self, cref):
        """Sets the cref of this MembersApiViewModel.


        :param cref: The cref of this MembersApiViewModel.  # noqa: E501
        :type: str
        """

        self._cref = cref

    @property
    def cref_expiration_date(self):
        """Gets the cref_expiration_date of this MembersApiViewModel.  # noqa: E501


        :return: The cref_expiration_date of this MembersApiViewModel.  # noqa: E501
        :rtype: datetime
        """
        return self._cref_expiration_date

    @cref_expiration_date.setter
    def cref_expiration_date(self, cref_expiration_date):
        """Sets the cref_expiration_date of this MembersApiViewModel.


        :param cref_expiration_date: The cref_expiration_date of this MembersApiViewModel.  # noqa: E501
        :type: datetime
        """

        self._cref_expiration_date = cref_expiration_date

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(MembersApiViewModel, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, MembersApiViewModel):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
