# coding: utf-8

"""
    EVO API

    Use the DNS of your gym as the User and the Secret Key as the password.The authentication method used in the integration is Basic Authentication  # noqa: E501

    OpenAPI spec version: v1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class W12UtilzWebHookFilterViewModel(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'filter_type': 'str',
        'value': 'str'
    }

    attribute_map = {
        'filter_type': 'filterType',
        'value': 'value'
    }

    def __init__(self, filter_type=None, value=None):  # noqa: E501
        """W12UtilzWebHookFilterViewModel - a model defined in Swagger"""  # noqa: E501
        self._filter_type = None
        self._value = None
        self.discriminator = None
        if filter_type is not None:
            self.filter_type = filter_type
        if value is not None:
            self.value = value

    @property
    def filter_type(self):
        """Gets the filter_type of this W12UtilzWebHookFilterViewModel.  # noqa: E501


        :return: The filter_type of this W12UtilzWebHookFilterViewModel.  # noqa: E501
        :rtype: str
        """
        return self._filter_type

    @filter_type.setter
    def filter_type(self, filter_type):
        """Sets the filter_type of this W12UtilzWebHookFilterViewModel.


        :param filter_type: The filter_type of this W12UtilzWebHookFilterViewModel.  # noqa: E501
        :type: str
        """

        self._filter_type = filter_type

    @property
    def value(self):
        """Gets the value of this W12UtilzWebHookFilterViewModel.  # noqa: E501


        :return: The value of this W12UtilzWebHookFilterViewModel.  # noqa: E501
        :rtype: str
        """
        return self._value

    @value.setter
    def value(self, value):
        """Sets the value of this W12UtilzWebHookFilterViewModel.


        :param value: The value of this W12UtilzWebHookFilterViewModel.  # noqa: E501
        :type: str
        """

        self._value = value

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(W12UtilzWebHookFilterViewModel, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, W12UtilzWebHookFilterViewModel):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
