# coding: utf-8

"""
    EVO API

    Use the DNS of your gym as the User and the Secret Key as the password.The authentication method used in the integration is Basic Authentication  # noqa: E501

    OpenAPI spec version: v1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class W12UtilsWebhookHeaderViewModel(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'nome': 'str',
        'valor': 'str'
    }

    attribute_map = {
        'nome': 'nome',
        'valor': 'valor'
    }

    def __init__(self, nome=None, valor=None):  # noqa: E501
        """W12UtilsWebhookHeaderViewModel - a model defined in Swagger"""  # noqa: E501
        self._nome = None
        self._valor = None
        self.discriminator = None
        if nome is not None:
            self.nome = nome
        if valor is not None:
            self.valor = valor

    @property
    def nome(self):
        """Gets the nome of this W12UtilsWebhookHeaderViewModel.  # noqa: E501


        :return: The nome of this W12UtilsWebhookHeaderViewModel.  # noqa: E501
        :rtype: str
        """
        return self._nome

    @nome.setter
    def nome(self, nome):
        """Sets the nome of this W12UtilsWebhookHeaderViewModel.


        :param nome: The nome of this W12UtilsWebhookHeaderViewModel.  # noqa: E501
        :type: str
        """

        self._nome = nome

    @property
    def valor(self):
        """Gets the valor of this W12UtilsWebhookHeaderViewModel.  # noqa: E501


        :return: The valor of this W12UtilsWebhookHeaderViewModel.  # noqa: E501
        :rtype: str
        """
        return self._valor

    @valor.setter
    def valor(self, valor):
        """Sets the valor of this W12UtilsWebhookHeaderViewModel.


        :param valor: The valor of this W12UtilsWebhookHeaderViewModel.  # noqa: E501
        :type: str
        """

        self._valor = valor

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(W12UtilsWebhookHeaderViewModel, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, W12UtilsWebhookHeaderViewModel):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
