# coding: utf-8

# flake8: noqa
"""
    EVO API

    Use the DNS of your gym as the User and the Secret Key as the password.The authentication method used in the integration is Basic Authentication  # noqa: E501

    OpenAPI spec version: v1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

# import models into model package
from evo_client.models.atividade_agenda_api_view_model import (
    AtividadeAgendaApiViewModel,
)
from evo_client.models.atividade_basico_api_view_model import (
    AtividadeBasicoApiViewModel,
)
from evo_client.models.atividade_list_api_view_model import AtividadeListApiViewModel
from evo_client.models.atividade_lugar_reserva_api_view_model import (
    AtividadeLugarReservaApiViewModel,
)
from evo_client.models.atividade_lugar_reserva_view_model import (
    AtividadeLugarReservaViewModel,
)
from evo_client.models.atividade_sessao_participante_api_view_model import (
    AtividadeSessaoParticipanteApiViewModel,
)
from evo_client.models.bandeiras_basico_view_model import BandeirasBasicoViewModel
from evo_client.models.bank_accounts_view_model import BankAccountsViewModel
from evo_client.models.basic_freeze_view_model import BasicFreezeViewModel
from evo_client.models.basic_member_membership_api_view_model import (
    BasicMemberMembershipApiViewModel,
)
from evo_client.models.bonus_session_view_model import BonusSessionViewModel
from evo_client.models.business_hours_view_model import BusinessHoursViewModel
from evo_client.models.card_data_view_model import CardDataViewModel
from evo_client.models.cliente_detalhes_basicos_api_view_model import (
    ClienteDetalhesBasicosApiViewModel,
)
from evo_client.models.cliente_enotas_retorno import ClienteEnotasRetorno
from evo_client.models.cliente_transferencia_view_model import (
    ClienteTransferenciaViewModel,
)
from evo_client.models.clientes_ativos_view_model import ClientesAtivosViewModel
from evo_client.models.configuracao_api_view_model import ConfiguracaoApiViewModel
from evo_client.models.contrato_entradas_api_view_model import (
    ContratoEntradasApiViewModel,
)
from evo_client.models.contrato_filiais_resumo_api_view_model import (
    ContratoFiliaisResumoApiViewModel,
)
from evo_client.models.contrato_nao_renovados_view_model import (
    ContratoNaoRenovadosViewModel,
)
from evo_client.models.contratos_cancelados_parcelas_api_view_model import (
    ContratosCanceladosParcelasApiViewModel,
)
from evo_client.models.contratos_cancelados_resumo_api_view_model import (
    ContratosCanceladosResumoApiViewModel,
)
from evo_client.models.contratos_resumo_api_view_model import (
    ContratosResumoApiViewModel,
)
from evo_client.models.contratos_resumo_pagina_venda_view_model import (
    ContratosResumoPaginaVendaViewModel,
)
from evo_client.models.convenios_api_view_model import ConveniosApiViewModel
from evo_client.models.cost_center_api_view_model import CostCenterApiViewModel
from evo_client.models.dados_contrato_trasnferencia_api_view_model import (
    DadosContratoTrasnferenciaApiViewModel,
)
from evo_client.models.dados_troca_contrato_api_view_model import (
    DadosTrocaContratoApiViewModel,
)
from evo_client.models.diferenciais_api_view_model import DiferenciaisApiViewModel
from evo_client.models.differentials_view_model import DifferentialsViewModel
from evo_client.models.e_forma_contato import EFormaContato
from evo_client.models.e_forma_pagamento_totem import EFormaPagamentoTotem
from evo_client.models.e_origem_agendamento import EOrigemAgendamento
from evo_client.models.e_status_atividade import EStatusAtividade
from evo_client.models.e_status_atividade_sessao import EStatusAtividadeSessao
from evo_client.models.e_tipo_contrato import ETipoContrato
from evo_client.models.e_tipo_gateway import ETipoGateway
from evo_client.models.employee_api_integracao_atualizacao_view_model import (
    EmployeeApiIntegracaoAtualizacaoViewModel,
)
from evo_client.models.employee_api_integracao_view_model import (
    EmployeeApiIntegracaoViewModel,
)
from evo_client.models.empresas_convenios_api_view_model import (
    EmpresasConveniosApiViewModel,
)
from evo_client.models.empresas_filiais_gateway_view_model import (
    EmpresasFiliaisGatewayViewModel,
)
from evo_client.models.empresas_filiais_ocupacao_view_model import (
    EmpresasFiliaisOcupacaoViewModel,
)
from evo_client.models.endereco_enotas_retorno import EnderecoEnotasRetorno
from evo_client.models.enotas_retorno import EnotasRetorno
from evo_client.models.entradas_resumo_api_view_model import EntradasResumoApiViewModel
from evo_client.models.freeze_view_model import FreezeViewModel
from evo_client.models.funcionarios_resumo_api_view_model import (
    FuncionariosResumoApiViewModel,
)
from evo_client.models.http_response_error import HttpResponseError
from evo_client.models.installment_view_model import InstallmentViewModel
from evo_client.models.log_tef_api_view_model import LogTefApiViewModel
from evo_client.models.member_authenticate_view_model import MemberAuthenticateViewModel
from evo_client.models.member_basic_responsible_view_model import (
    MemberBasicResponsibleViewModel,
)
from evo_client.models.member_data_view_model import MemberDataViewModel
from evo_client.models.member_membership_api_view_model import (
    MemberMembershipApiViewModel,
)
from evo_client.models.member_new_sale_view_model import MemberNewSaleViewModel
from evo_client.models.member_responsible_view_model import MemberResponsibleViewModel
from evo_client.models.member_service_view_model import MemberServiceViewModel
from evo_client.models.members_api_view_model import MembersApiViewModel
from evo_client.models.members_basic_api_view_model import MembersBasicApiViewModel
from evo_client.models.metadados_enotas_retorno import MetadadosEnotasRetorno
from evo_client.models.month_discount_view_model import MonthDiscountViewModel
from evo_client.models.new_sale_view_model import NewSaleViewModel
from evo_client.models.notification_api_view_model import NotificationApiViewModel
from evo_client.models.payables_api_sub_types_view_model import (
    PayablesApiSubTypesViewModel,
)
from evo_client.models.payables_api_view_model import PayablesApiViewModel
from evo_client.models.periodizacao_api_view_model import PeriodizacaoApiViewModel
from evo_client.models.pix_payment_details_view_model import PixPaymentDetailsViewModel
from evo_client.models.prospect_api_integracao_atualizacao_view_model import (
    ProspectApiIntegracaoAtualizacaoViewModel,
)
from evo_client.models.prospect_api_integracao_view_model import (
    ProspectApiIntegracaoViewModel,
)
from evo_client.models.prospect_id_view_model import ProspectIdViewModel
from evo_client.models.prospect_responsavel_resumo_api_view_model import (
    ProspectResponsavelResumoApiViewModel,
)
from evo_client.models.prospect_transferencia_view_model import (
    ProspectTransferenciaViewModel,
)
from evo_client.models.prospects_resumo_api_view_model import (
    ProspectsResumoApiViewModel,
)
from evo_client.models.publico_atividade_view_model import PublicoAtividadeViewModel
from evo_client.models.receivables_api_sub_types_view_model import (
    ReceivablesApiSubTypesViewModel,
)
from evo_client.models.receivables_api_view_model import ReceivablesApiViewModel
from evo_client.models.receivables_credit_details import ReceivablesCreditDetails
from evo_client.models.receivables_invoice_api_view_model import (
    ReceivablesInvoiceApiViewModel,
)
from evo_client.models.receivables_mask_received_view_model import (
    ReceivablesMaskReceivedViewModel,
)
from evo_client.models.revenue_center_api_view_model import RevenueCenterApiViewModel
from evo_client.models.sale_itens_view_model import SaleItensViewModel
from evo_client.models.sales_item_view_model import SalesItemViewModel
from evo_client.models.sales_items_view_model import SalesItemsViewModel
from evo_client.models.sales_view_model import SalesViewModel
from evo_client.models.service_discount_view_model import ServiceDiscountViewModel
from evo_client.models.servico_adicional_api_view_model import (
    ServicoAdicionalApiViewModel,
)
from evo_client.models.servico_anual_api_view_model import ServicoAnualApiViewModel
from evo_client.models.servico_enotas_retorno import ServicoEnotasRetorno
from evo_client.models.servicos_resumo_api_view_model import ServicosResumoApiViewModel
from evo_client.models.sps_rel_prospects_cadastrados_convertidos import (
    SpsRelProspectsCadastradosConvertidos,
)
from evo_client.models.tax_data_view_model import TaxDataViewModel
from evo_client.models.telefone_api_view_model import TelefoneApiViewModel
from evo_client.models.vouchers_resumo_api_view_model import VouchersResumoApiViewModel
from evo_client.models.w12_utils_category_membership_view_model import (
    W12UtilsCategoryMembershipViewModel,
)
from evo_client.models.w12_utils_webhook_filter_view_model import (
    W12UtilsWebhookFilterViewModel,
)
from evo_client.models.w12_utils_webhook_header_view_model import (
    W12UtilsWebhookHeaderViewModel,
)
from evo_client.models.w12_utils_webhook_view_model import W12UtilsWebhookViewModel
from evo_client.models.year_discount_view_model import YearDiscountViewModel
