# coding: utf-8

"""
    EVO API

    Use the DNS of your gym as the User and the Secret Key as the password.The authentication method used in the integration is Basic Authentication  # noqa: E501
"""

from datetime import datetime
from typing import List, Optional

from pydantic import BaseModel, Field, ConfigDict

from .atividade_lugar_reserva_api_view_model import AtividadeLugarReservaApiViewModel
from .e_status_atividade import EStatusAtividade
from .periodizacao_api_view_model import PeriodizacaoApiViewModel


class AtividadeAgendaApiViewModel(BaseModel):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    model_config = ConfigDict(populate_by_name=True)

    id_configuration: Optional[int] = Field(default=None, alias="idConfiguration")
    id_activity: Optional[int] = Field(default=None, alias="idActivity")
    id_group_activity: Optional[int] = Field(default=None, alias="idGroupActivity")
    name: Optional[str] = None
    description: Optional[str] = None
    image_url: Optional[str] = Field(default=None, alias="imageUrl")
    area: Optional[str] = None
    id_area: Optional[int] = Field(default=None, alias="idArea")
    capacity: Optional[int] = None
    ocupation: Optional[int] = None
    allow_choosing_spot: Optional[bool] = Field(default=None, alias="allowChoosingSpot")
    start_time: Optional[str] = Field(default=None, alias="startTime")
    end_time: Optional[str] = Field(default=None, alias="endTime")
    booking_start_time: Optional[str] = Field(default=None, alias="bookingStartTime")
    booking_end_time: Optional[str] = Field(default=None, alias="bookingEndTime")
    instructor: Optional[str] = None
    instructor_photo: Optional[str] = Field(default=None, alias="instructorPhoto")
    activity_date: Optional[datetime] = Field(default=None, alias="activityDate")
    audience: Optional[str] = None
    id_audience: Optional[int] = Field(default=None, alias="idAudience")
    code: Optional[str] = None
    confirmed: Optional[bool] = None
    start_hour_tick: Optional[int] = Field(default=None, alias="startHourTick")
    end_hour_tick: Optional[int] = Field(default=None, alias="endHourTick")
    spots: Optional[List[AtividadeLugarReservaApiViewModel]] = None
    periodization: Optional[List[PeriodizacaoApiViewModel]] = None
    status: Optional[EStatusAtividade] = None
    status_name: Optional[str] = Field(default=None, alias="statusName")

    def to_dict(self):
        """Returns the model properties as a dict"""
        return self.model_dump(by_alias=True)
