from datetime import datetime
from typing import Optional
from pydantic import BaseModel, Field


class ClientesAtivosViewModel(BaseModel):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    id_filial: Optional[int] = Field(default=None, alias="idFilial")
    filial: Optional[str] = None
    id_cliente: Optional[int] = Field(default=None, alias="idCliente")
    nome_completo: Optional[str] = Field(default=None, alias="nomeCompleto")
    telefone: Optional[str] = None
    email: Optional[str] = None
    id_cliente_contrato_ativo: Optional[int] = Field(
        default=None, alias="idClienteContratoAtivo"
    )
    contrato_ativo: Optional[str] = Field(default=None, alias="contratoAtivo")
    dt_inicio_contrato_ativo: Optional[datetime] = Field(
        default=None, alias="dtInicioContratoAtivo"
    )
    dt_fim_contrato_ativo: Optional[datetime] = Field(
        default=None, alias="dtFimContratoAtivo"
    )
    id_cliente_contrato_futuro: Optional[int] = Field(
        default=None, alias="idClienteContratoFuturo"
    )
    contrato_futuro: Optional[str] = Field(default=None, alias="contratoFuturo")
    dt_inicio_contrato_futuro: Optional[datetime] = Field(
        default=None, alias="dtInicioContratoFuturo"
    )
    dt_fim_contrato_futuro: Optional[datetime] = Field(
        default=None, alias="dtFimContratoFuturo"
    )

    def to_dict(self):
        """Returns the model properties as a dict"""
        return self.model_dump(by_alias=True)

    def to_str(self):
        """Returns the string representation of the model"""
        return str(self.model_dump())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, ClientesAtivosViewModel):
            return False

        return self.model_dump() == other.model_dump()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
