from datetime import datetime
from typing import Optional
from pydantic import BaseModel, Field


class ContratoNaoRenovadosViewModel(BaseModel):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    id_filial: Optional[int] = Field(default=None, alias="idFilial")
    nome_filial: Optional[str] = Field(default=None, alias="nomeFilial")
    id_cliente: Optional[int] = Field(default=None, alias="idCliente")
    status: Optional[str] = None
    contrato_ativo: Optional[str] = Field(default=None, alias="contratoAtivo")
    nome: Optional[str] = None
    sobrenome: Optional[str] = None
    contrato_vencido: Optional[str] = Field(default=None, alias="contratoVencido")
    data_inicio: Optional[datetime] = Field(default=None, alias="dataInicio")
    data_fim: Optional[datetime] = Field(default=None, alias="dataFim")
    meses_permanencia: Optional[int] = Field(default=None, alias="mesesPermanencia")
    valor: Optional[float] = None
    fl_cancelado: Optional[bool] = Field(default=None, alias="flCancelado")
    dt_cancelamento: Optional[datetime] = Field(default=None, alias="dtCancelamento")
    contrato_cancelado: Optional[str] = Field(default=None, alias="contratoCancelado")
    motivo_cancelamento: Optional[str] = Field(default=None, alias="motivoCancelamento")
    nome_consultor: Optional[str] = Field(default=None, alias="nomeConsultor")
    celular: Optional[str] = None
    email: Optional[str] = None

    def to_dict(self):
        """Returns the model properties as a dict"""
        return self.model_dump(by_alias=True)

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, ContratoNaoRenovadosViewModel):
            return False

        return self.model_dump() == other.model_dump()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
