name: Code Formatter

on:
  workflow_call:

jobs:
  build:
    name: Code Formatter
    runs-on: ubuntu-latest

    steps:
      - name: Set env.BRANCH
        run: echo "BRANCH=$(echo $GITHUB_REF | cut -d'/' -f 3)" >> $GITHUB_ENV

      - name: Checkout repo
        uses: actions/checkout@v4 
        with:
          repository: ${{ github.repository }}

      - name: Set up Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: 3.11
          check-latest: true
          
      # https://github.com/myint/autoflake
      - name: Install autoflake
        run: |
          python -m pip install --upgrade autoflake
      - name: Removing unused variables and imports
        run: |
          autoflake src/ tests/ --remove-unused-variables --remove-all-unused-imports --ignore-init-module-imports --recursive --in-place

      # https://github.com/PyCQA/isort
      # https://github.com/isort/isort-action
      - uses: isort/isort-action@master
        with:
          sort-paths: "src/ tests/"
          configuration: "--atomic"

      # https://github.com/rickstaa/action-black/
      - name: Check files using the black formatter
        uses: rickstaa/action-black@v1
        id: action_black
        with:
          black_args: "src/ tests/"

      - name: Create Pull Request
        id: cpr
        if: steps.action_black.outputs.is_formatted == 'true'
        uses: peter-evans/create-pull-request@v7
        with:
          # token criado no jquantinho
          # https://github.com/peter-evans/create-pull-request/issues/48#issuecomment-537478081
          token: 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
          title: "Format Python code with psf/black push"
          commit-message: ":art: Format Python code with psf/black"
          body: |
            There appear to be some python formatting errors in ${{ github.sha }}. This pull request
            uses the [psf/black](https://github.com/psf/black) formatter to fix these issues.
          base: ${{ github.head_ref }} # Creates pull request onto pull request or commit branch
          branch: actions-black/${{ env.BRANCH }}

      - name: Create Comment
        if: ${{ steps.cpr.outputs.pull-request-number }}
        uses: actions/github-script@v6
        with:
          script: |
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: 'A **new** [pull request](${{ steps.cpr.outputs.pull-request-url }}) has been created to format the Python code from this Pull Request. :art:\nPlease review the changes and merge the pull request #${{ steps.cpr.outputs.pull-request-number }} before merging the current pull request. :+1:'
            })